# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "/home/ian-rider/eth_book_git_wa/ethernet_to_book/ethernet_to_book_proj/project/project.runs/synth_1/ethernet_to_book_top.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param chipscope.maxJobs 4
set_param general.usePosixSpawnForFork 1
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7a200tsbg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/ian-rider/eth_book_git_wa/ethernet_to_book/ethernet_to_book_proj/project/project.cache/wt [current_project]
set_property parent.project_path /home/ian-rider/eth_book_git_wa/ethernet_to_book/ethernet_to_book_proj/project/project.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo /home/ian-rider/eth_book_git_wa/ethernet_to_book/ethernet_to_book_proj/project/project.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_mem /home/ian-rider/eth_book_git_wa/ethernet_to_book/ethernet_to_book_proj/src/reuse/init_ram_zeros.mem
read_verilog -library xil_defaultlib -sv {
  /home/ian-rider/eth_book_git_wa/ethernet_to_book/ethernet_to_book_proj/src/clks_rsts.sv
  /home/ian-rider/eth_book_git_wa/ethernet_to_book/ethernet_to_book_proj/src/pkg.sv
  /home/ian-rider/eth_book_git_wa/ethernet_to_book/ethernet_to_book_proj/src/eth_udp_parser.sv
  /home/ian-rider/eth_book_git_wa/ethernet_to_book/ethernet_to_book_proj/src/itch_parser.sv
  /home/ian-rider/eth_book_git_wa/ethernet_to_book/ethernet_to_book_proj/src/order_book.sv
  /home/ian-rider/eth_book_git_wa/ethernet_to_book/ethernet_to_book_proj/src/order_map.sv
  /home/ian-rider/eth_book_git_wa/ethernet_to_book/ethernet_to_book_proj/src/order_book_engine.sv
  /home/ian-rider/eth_book_git_wa/ethernet_to_book/ethernet_to_book_proj/src/reuse/pipe.sv
  /home/ian-rider/eth_book_git_wa/ethernet_to_book/ethernet_to_book_proj/src/rgmii_rx.sv
  /home/ian-rider/eth_book_git_wa/ethernet_to_book/ethernet_to_book_proj/src/rgmii.sv
  /home/ian-rider/eth_book_git_wa/ethernet_to_book/ethernet_to_book_proj/src/slow_fast_cdc.sv
  /home/ian-rider/eth_book_git_wa/ethernet_to_book/ethernet_to_book_proj/src/ethernet_to_book_top.sv
}
read_ip -quiet /home/ian-rider/eth_book_git_wa/ethernet_to_book/ethernet_to_book_proj/project/project.srcs/sources_1/ip/system_clocks_gen/system_clocks_gen.xci
set_property used_in_implementation false [get_files -all /home/ian-rider/eth_book_git_wa/ethernet_to_book/ethernet_to_book_proj/project/project.gen/sources_1/ip/system_clocks_gen/system_clocks_gen_board.xdc]
set_property used_in_implementation false [get_files -all /home/ian-rider/eth_book_git_wa/ethernet_to_book/ethernet_to_book_proj/project/project.gen/sources_1/ip/system_clocks_gen/system_clocks_gen.xdc]
set_property used_in_implementation false [get_files -all /home/ian-rider/eth_book_git_wa/ethernet_to_book/ethernet_to_book_proj/project/project.gen/sources_1/ip/system_clocks_gen/system_clocks_gen_ooc.xdc]

read_ip -quiet /home/ian-rider/eth_book_git_wa/ethernet_to_book/ethernet_to_book_proj/project/project.srcs/sources_1/ip/rx_clk_shift/rx_clk_shift.xci
set_property used_in_implementation false [get_files -all /home/ian-rider/eth_book_git_wa/ethernet_to_book/ethernet_to_book_proj/project/project.gen/sources_1/ip/rx_clk_shift/rx_clk_shift_board.xdc]
set_property used_in_implementation false [get_files -all /home/ian-rider/eth_book_git_wa/ethernet_to_book/ethernet_to_book_proj/project/project.gen/sources_1/ip/rx_clk_shift/rx_clk_shift.xdc]
set_property used_in_implementation false [get_files -all /home/ian-rider/eth_book_git_wa/ethernet_to_book/ethernet_to_book_proj/project/project.gen/sources_1/ip/rx_clk_shift/rx_clk_shift_ooc.xdc]

read_ip -quiet /home/ian-rider/eth_book_git_wa/ethernet_to_book/ethernet_to_book_proj/project/project.srcs/sources_1/ip/top_of_book_ila/top_of_book_ila.xci
set_property used_in_synthesis false [get_files -all /home/ian-rider/eth_book_git_wa/ethernet_to_book/ethernet_to_book_proj/project/project.gen/sources_1/ip/top_of_book_ila/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all /home/ian-rider/eth_book_git_wa/ethernet_to_book/ethernet_to_book_proj/project/project.gen/sources_1/ip/top_of_book_ila/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all /home/ian-rider/eth_book_git_wa/ethernet_to_book/ethernet_to_book_proj/project/project.gen/sources_1/ip/top_of_book_ila/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all /home/ian-rider/eth_book_git_wa/ethernet_to_book/ethernet_to_book_proj/project/project.gen/sources_1/ip/top_of_book_ila/top_of_book_ila_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/ian-rider/eth_book_git_wa/ethernet_to_book/ethernet_to_book_proj/phys/area.xdc
set_property used_in_implementation false [get_files /home/ian-rider/eth_book_git_wa/ethernet_to_book/ethernet_to_book_proj/phys/area.xdc]

read_xdc /home/ian-rider/eth_book_git_wa/ethernet_to_book/ethernet_to_book_proj/phys/pins.xdc
set_property used_in_implementation false [get_files /home/ian-rider/eth_book_git_wa/ethernet_to_book/ethernet_to_book_proj/phys/pins.xdc]

read_xdc /home/ian-rider/eth_book_git_wa/ethernet_to_book/ethernet_to_book_proj/phys/time.xdc
set_property used_in_implementation false [get_files /home/ian-rider/eth_book_git_wa/ethernet_to_book/ethernet_to_book_proj/phys/time.xdc]

set_param ips.enableIPCacheLiteLoad 1

read_checkpoint -auto_incremental -incremental /home/ian-rider/eth_book_git_wa/ethernet_to_book/ethernet_to_book_proj/project/project.srcs/utils_1/imports/synth_1/ethernet_to_book_top.dcp
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top ethernet_to_book_top -part xc7a200tsbg484-1
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef ethernet_to_book_top.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
generate_parallel_reports -reports { "report_utilization -file ethernet_to_book_top_utilization_synth.rpt -pb ethernet_to_book_top_utilization_synth.pb"  } 
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
