# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/ian-rider/eth_book_git_wa/ethernet_to_book/ethernet_to_book_proj/project/project.srcs/sources_1/ip/rx_clk_shift/rx_clk_shift.xci
# IP: The module: 'rx_clk_shift' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/ian-rider/eth_book_git_wa/ethernet_to_book/ethernet_to_book_proj/project/project.gen/sources_1/ip/rx_clk_shift/rx_clk_shift_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'rx_clk_shift'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/ian-rider/eth_book_git_wa/ethernet_to_book/ethernet_to_book_proj/project/project.gen/sources_1/ip/rx_clk_shift/rx_clk_shift.xdc
# XDC: The top module name and the constraint reference have the same name: 'rx_clk_shift'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/ian-rider/eth_book_git_wa/ethernet_to_book/ethernet_to_book_proj/project/project.gen/sources_1/ip/rx_clk_shift/rx_clk_shift_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rx_clk_shift'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/ian-rider/eth_book_git_wa/ethernet_to_book/ethernet_to_book_proj/project/project.srcs/sources_1/ip/rx_clk_shift/rx_clk_shift.xci
# IP: The module: 'rx_clk_shift' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/ian-rider/eth_book_git_wa/ethernet_to_book/ethernet_to_book_proj/project/project.gen/sources_1/ip/rx_clk_shift/rx_clk_shift_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'rx_clk_shift'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/ian-rider/eth_book_git_wa/ethernet_to_book/ethernet_to_book_proj/project/project.gen/sources_1/ip/rx_clk_shift/rx_clk_shift.xdc
# XDC: The top module name and the constraint reference have the same name: 'rx_clk_shift'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/ian-rider/eth_book_git_wa/ethernet_to_book/ethernet_to_book_proj/project/project.gen/sources_1/ip/rx_clk_shift/rx_clk_shift_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rx_clk_shift'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
